import { Button, EmptyState, Field, LoadingState, Notice, Pager, StatusBadge, formatDate, useApiData, useApiForm } from '@/Components/AcademicUI';
import Modal from '@/Components/Modal';
import { DialogTitle } from '@headlessui/react';
import { useState } from 'react';

export default function MembersPanel({ kelasMapel, permissions }) {
    const base = `/api/v1/kelas-mapel/${kelasMapel.id}`;
    const [page, setPage] = useState(1);
    const [decision, setDecision] = useState(null);
    const members = useApiData(`${base}/anggota?page=${page}`);
    const teachers = useApiData(`${base}/whitelist`);
    const master = useApiData(permissions.update ? '/api/v1/master-data' : null);
    const review = useApiForm({});
    const whitelist = useApiForm({ guru_id: '', status: 'aktif' });
    async function confirm() {
        const result = await review.submit('patch', `${base}/anggota/${decision.member.id}`, { status: decision.status });
        if (result) { setDecision(null); members.reload(); }
    }
    async function saveTeacher(event) {
        event.preventDefault();
        const result = await whitelist.submit('post', `${base}/whitelist`);
        if (result) teachers.reload();
    }
    return <div className="flex flex-col gap-7"><section><div className="mb-5 flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold">Anggota kelas</h2><p className="mt-2 text-sm text-slate-500">{permissions.reviewMembers ? 'Tinjau permintaan sebelum siswa dapat mengikuti kegiatan.' : 'Daftar siswa dan status keanggotaan kelas.'}</p></div><Button variant="secondary" onClick={members.reload}>Perbarui</Button></div><Notice tone="success" message={review.message} />
        {members.loading ? <LoadingState /> : members.error ? <Notice message={members.error} /> : <>{members.data?.data?.data?.length ? <div className="surface overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-4">Siswa / NIS</th><th className="p-4">Pengajuan</th><th className="p-4">Status</th>{permissions.reviewMembers && <th className="p-4">Tindakan</th>}</tr></thead><tbody>{members.data.data.data.map((member) => <tr key={member.id} className="border-t border-slate-100"><td className="p-4"><p className="font-semibold">{member.siswa?.nama_lengkap}</p><p className="mt-1 text-xs text-slate-500">{member.siswa?.nis || 'NIS belum diisi'}</p></td><td className="p-4 text-xs text-slate-500">{formatDate(member.requested_at)}<span className="mt-1 block">Melalui {member.join_method === 'link' ? 'link' : 'kode kelas'}</span></td><td className="p-4"><StatusBadge status={member.status} /></td>{permissions.reviewMembers && <td className="p-4">{member.status === 'pending' ? <div className="flex gap-2"><Button onClick={() => { review.setData({}); setDecision({ member, status: 'diterima' }); }}>Terima</Button><Button variant="danger" onClick={() => { review.setData({}); setDecision({ member, status: 'ditolak' }); }}>Tolak</Button></div> : <span className="text-xs text-slate-400">Sudah ditinjau</span>}</td>}</tr>)}</tbody></table></div> : <EmptyState title="Belum ada anggota" description="Bagikan kode atau link undangan kelas agar siswa dapat mengajukan bergabung." />}<Pager meta={members.data?.data} onPage={setPage} /></>}
    </section><section className="flex flex-col gap-4"><div><h2 className="text-xl font-bold">Guru yang memiliki akses</h2><p className="mt-2 text-sm text-slate-500">Guru mapel mengelola kegiatan; guru piket memantau siswa dan pengumpulan.</p></div>{teachers.loading ? <LoadingState /> : teachers.error ? <><Notice message={teachers.error} /><Button variant="secondary" onClick={teachers.reload}>Coba lagi</Button></> : <div className="surface divide-y divide-slate-100">{teachers.data?.data?.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 p-5"><div><p className="text-sm font-bold">{item.guru?.nama_lengkap}{item.guru_id === kelasMapel.guru_pembuat_id ? ' · Pemilik' : ''}</p><p className="mt-1 text-xs text-slate-500">{item.guru?.jenis_guru === 'guru_piket' ? 'Guru piket' : 'Guru mata pelajaran'}</p></div><StatusBadge status={item.status} /></div>)}</div>}
        {permissions.update && <form onSubmit={saveTeacher} className="surface flex flex-col gap-4 p-6"><h3 className="font-bold">Atur akses guru</h3>{master.error && <><Notice message={master.error} /><Button variant="secondary" onClick={master.reload}>Muat daftar guru</Button></>}<div className="grid gap-4 sm:grid-cols-2"><Field label="Guru" error={whitelist.errors.guru_id}><select className="input" required value={whitelist.data.guru_id} onChange={(e) => whitelist.setData('guru_id', e.target.value)}><option value="">{master.loading ? 'Memuat...' : 'Pilih guru'}</option>{master.data?.guru?.filter((item) => item.id !== kelasMapel.guru_pembuat_id).map((item) => <option key={item.id} value={item.id}>{item.nama_lengkap} · {item.jenis_guru === 'guru_piket' ? 'Piket' : 'Mapel'}</option>)}</select></Field><Field label="Status akses" error={whitelist.errors.status}><select className="input" value={whitelist.data.status} onChange={(e) => whitelist.setData('status', e.target.value)}><option value="aktif">Aktif — izinkan akses</option><option value="nonaktif">Nonaktif — cabut akses</option></select></Field></div><Notice message={whitelist.errors._general} /><Notice tone="success" message={whitelist.message} /><Button className="self-start" type="submit" disabled={whitelist.processing || master.loading || Boolean(master.error)}>{whitelist.processing ? 'Menyimpan...' : 'Simpan akses guru'}</Button></form>}
    </section><Modal show={Boolean(decision)} onClose={() => !review.processing && setDecision(null)} closeable={!review.processing} maxWidth="md"><div className="flex flex-col gap-4 p-6"><DialogTitle className="text-lg font-bold">{decision?.status === 'diterima' ? 'Terima siswa?' : 'Tolak permintaan?'}</DialogTitle><p className="text-sm leading-6 text-slate-600">{decision?.member.siswa?.nama_lengkap} {decision?.status === 'diterima' ? 'akan mendapat akses ke tugas, ujian, dan kegiatan kelas ini.' : 'tidak mendapat akses ke kelas ini dan dapat mengajukan kembali.'}</p><Notice message={review.errors._general || review.errors.status} /><div className="flex justify-end gap-3"><Button variant="secondary" disabled={review.processing} onClick={() => setDecision(null)}>Batal</Button><Button variant={decision?.status === 'ditolak' ? 'danger' : 'primary'} disabled={review.processing} onClick={confirm}>{review.processing ? 'Memproses...' : 'Ya, lanjutkan'}</Button></div></div></Modal></div>;
}
