import { EmptyState } from '@/Components/AcademicUI';
import Icon from '@/Components/Icon';
import StudentLayout from '@/Layouts/StudentLayout';
import { Head, Link, usePage } from '@inertiajs/react';

export default function TeacherDashboard({ stats, rooms, requests }) {
    const user = usePage().props.auth.user;
    const teacher = user.guru?.jenis_guru === 'guru_mapel';
    const cards = [['Kelas aktif', stats.kelas, 'book'], ['Siswa terdaftar', stats.siswa, 'user'], ['Menunggu persetujuan', stats.pending, 'clock'], ['Tugas dikumpulkan', stats.pengumpulan, 'clipboard']];
    return <StudentLayout title="Beranda guru"><Head title="Beranda Guru" /><div className="mb-7"><p className="eyebrow mb-2">{teacher ? 'Ruang mengajar' : 'Ruang pemantauan'}</p><h1 className="text-3xl font-extrabold">Selamat datang, {user.name}</h1><p className="mt-2 text-sm text-slate-500">{teacher ? 'Kelola pembelajaran dan bantu setiap siswa berkembang.' : 'Pantau kelas, tugas, dan pengumpulan siswa yang menjadi tanggung jawab Anda.'}</p></div>
        <section className="hero-pattern mb-7 flex flex-wrap items-center justify-between gap-6 rounded-3xl bg-[#142E36] p-7 text-white sm:p-9"><div><h2 className="text-2xl font-bold">Satu ruang untuk<br /><span className="text-teal-200">kegiatan belajar yang teratur.</span></h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300">{teacher ? 'Siapkan kelas, terima siswa, bagikan tugas, dan pantau hasil belajarnya.' : 'Seluruh data di sini mengikuti akses kelas yang diberikan pemilik kelas.'}</p></div><Link href={route('subjects.index')} className="rounded-xl bg-white px-5 py-3 text-sm font-bold text-teal-900">{teacher ? 'Kelola mata pelajaran' : 'Lihat kelas'}</Link></section>
        <div className="mb-8 grid grid-cols-2 gap-4 xl:grid-cols-4">{cards.map(([label, value, icon]) => <section key={label} className="surface p-5"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold text-slate-500">{label}</p><Icon name={icon} className="h-5 w-5 text-teal-600" /></div><p className="mt-4 text-3xl font-extrabold">{value}</p></section>)}</div>
        <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><section><div className="mb-4 flex justify-between gap-3"><h2 className="text-lg font-bold">Kelas Anda</h2><Link className="text-sm font-bold text-teal-700" href={route('subjects.index')}>Lihat semua</Link></div>{rooms.length ? <div className="grid gap-4 sm:grid-cols-2">{rooms.map((room) => <Link className="surface p-6 transition hover:border-teal-300" key={room.id} href={route('subjects.show', { subject: room.id })}><p className="text-xs font-bold text-teal-700">{room.mapel?.nama_mapel}</p><h3 className="mt-3 text-lg font-bold">{room.nama_kelas_mapel}</h3><p className="mt-3 text-sm text-slate-500">{room.tugas_count} tugas</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-teal-700">Buka kelas <Icon name="arrow" className="h-4 w-4" /></span></Link>)}</div> : <EmptyState title="Belum ada kelas" description={teacher ? 'Buat kelas mata pelajaran pertama Anda untuk memulai.' : 'Minta pemilik kelas menambahkan Anda ke daftar guru yang memiliki akses.'} />}</section><section className="surface p-6"><h2 className="font-bold">Permintaan bergabung</h2><p className="mt-2 text-xs leading-5 text-slate-500">Permintaan terbaru di kelas milik Anda.</p><div className="mt-5 flex flex-col gap-4">{requests.length ? requests.map((entry) => <Link href={route('subjects.section', { subject: entry.kelas_mapel_id, section: 'anggota' })} key={entry.id} className="rounded-xl border border-slate-100 p-4 hover:bg-teal-50"><p className="text-sm font-bold">{entry.siswa?.nama_lengkap}</p><p className="mt-1 text-xs text-slate-500">{entry.kelas_mapel?.nama_kelas_mapel}</p><span className="mt-3 inline-block text-xs font-bold text-teal-700">Tinjau permintaan →</span></Link>) : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Tidak ada permintaan yang menunggu.</p>}</div></section></div>
    </StudentLayout>;
}
